name: Update GitHub Profile Stats

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Stats
        run: |
          curl -sS https://github-readme-stats-rmcl.vercel.app/api?username=Viniciusulpicio&show_icons=true&count_private=true&include_all_commits=true&hide_border=true&title_color=9400D3&icon_color=9400D3&text_color=c9d1d9&bg_color=0d1117 > /dev/null
          curl -sS https://github-readme-stats-rmcl.vercel.app/api/top-langs/?username=Viniciusulpicio&layout=compact&hide_border=true&title_color=9400D3&text_color=c9d1d9&bg_color=0d1117 > /dev/null