name: Update GitHub Profile Stats

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Stats
        run: |
          # Substitua 'YOUR-USERNAME' pelo seu nome de usuário do GitHub
          curl -sS https://github-readme-stats-rmcl.vercel.app/api?username=YOUR-USERNAME > /dev/null
          curl -sS https://github-readme-stats-rmcl.vercel.app/api/top-langs/?username=YOUR-USERNAME > /dev/null